//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcBlogDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorum
    {
        public int id { get; set; }
        public string icerik { get; set; }
        public Nullable<int> uye_id { get; set; }
        public Nullable<int> makale_id { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    
        public virtual Makale Makale { get; set; }
        public virtual Uye Uye { get; set; }
    }
}
